version: '3.8'

networks:
  api-network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: car_db
    networks:
      - api-network
    environment:
      POSTGRES_USER: carapp
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cardb
    ports:
      - "15432:5432"
    volumes:
      - ./init_sql/init01.sql:/docker-entrypoint-initdb.d/init01.sql
  app:
    image: "car_api"
    networks:
      - api-network
    build:
      context: .
    container_name: car_api
    depends_on:
      - db
    ports:
      - "8081:8080"