spring:
  application:
    name: eletriccar_api
  jpa:
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: null
    hibernate:
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  datasource:
#    url: jdbc:postgresql://db:5432/cardb?currentSchema=eletriccar # para caso de uso via docker-compose
    url: jdbc:postgresql://172.18.0.2:5432/cardb?currentSchema=eletriccar # para containers construídos na mão
#    url: jdbc:postgresql://localhost:5432/cardb?currentSchema=eletriccar # para execução toda local (necessário instalar configurar o sgbd na máquina host)
    username: carapp
    password: secret
    driver-class-name: org.postgresql.Driver