spring:
  application:
    name: eletriccar_api
  jpa:
    properties:
      hibernate:
        transaction:
          jta:
            platform: null
    hibernate:
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    hibernate:
#      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:eletric_cars_db
    username: app
#    password: pass123
