spring:
  application:
    name: eletriccar_api
  jpa:
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: null
    hibernate:
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/cardb?currentSchema=eletriccar
    username: carapp
    password: secret
    driver-class-name: org.postgresql.Driver